name: Suggest a Feature
description: You have an idea for block, item, mob, biome or maybe even an entire dimension? Submit it here!\
title: "Feature: <Title>"
labels: ["Type: feature"]
body:
- type: dropdown
  attributes:
    label: Which component should be improved?
    options: [Audio, Rendering, Entity, Gameplay, UI/UX, Hammer, Tools, Other]
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your feature suggestion in more detail
    description: Feel free to add pictures or video directly to this description!
    placeholder: |
      Give a clear explanation of what you want us to add. 
      Please don't give vague suggestions like "Make button look better" or "Add entity that damages the player".
      How exactly does it work? What are the inputs? What is the expected outcome?
  validations:
    required: true